# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- azure

stages:
- stage: build
  jobs:
  - job: run_node_steps
    pool:
      name: Default
    container: node:8
    steps:
    - script: | 
        yarn install
        yarn test
      displayName: 'yarn install and test'