# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- azure

stages:
- stage: build
  jobs:
  - job: run_node_steps
    pool:
      name: Default
    container: node:8
    steps:
    - script: | 
        yarn install
        yarn test
      displayName: 'yarn install and test'

- stage: apps
  jobs:
  - job: android
    pool:
      name: Default
    container: openjdk:8-jdk
    steps:
    - script: | 
        echo hello android
  - job: ios
    pool:
      name: macos-ix-laptop
    steps:
    - script: | 
        echo hello ios

- stage: stage3
  jobs:
  - job: stage3_job
    pool:
      name: Default
    steps:
    - script: echo stage3
      displayName: 'echo stage3'

- stage: stage4
  jobs:
  - job: stage4_job
    pool:
      name: Default
    steps:
    - script: echo stage4
      displayName: 'echo stage4'

- stage: stage5
  jobs:
  - job: stage5_job
    pool:
      name: Default
    steps:
    - script: echo stage5
      displayName: 'echo stage5'