version: 0.2

phases:
  install:
    commands:
      - echo Testing with a buildspec.yml file
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - yarn install
  post_build:
    commands:
      - echo Build completed on `date`