# BuildKite Pipeline

steps:
  - label: "hello"
    command: "echo \"hello\""

  - label: "run tests"
    commands:
      - "yarn install"
      - "yarn run test"
    plugins:
      - docker#v3.1.0:
          image: "node:10"  

  - label: "check node version"
    command: "node --version"
    plugins:
      - docker#v3.1.0:
          image: "node:10"  