# BuildKite Pipeline

steps:
  - command: "echo \"hello\""
    plugins:
      - docker#v3.1.0:
          image: "node:10"
      - jobready/codeclimate-test-reporter#v2.0:
          artifact: "coverage/.resultset.json"
          input_type: simplecov
          prefix: /app